In [ ]:
#Q.1 Create a numpy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
import numpy as np

arr = np.arange(6)

print(arr.dtype)

int64


In [ ]:
#Q.2 Given a numpy array 'arr', check if its data type is float64. arr = np.array([1.5, 2.6, 3.7])

In [ ]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("The data type of the array is float64.")
else:
    print("The data type of the array is not float64.")

The data type of the array is float64.


In [ ]:
#Q.3 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
import numpy as np

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [ ]:
#Q.4 Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

arr_float32 = arr.astype(np.float32)

print("Converted Array:", arr_float32)
print("Data type:", arr_float32.dtype)

Converted Array: [1. 2. 3. 4. 5.]
Data type: float32


In [ ]:
#Q.5 Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np

arr = np.array([1.123456789, 2.987654321], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

print(arr_float32)

[1.1234568 2.9876542]


In [ ]:
#Q.6 Write a function array_attributes that takes a NumPy array as input and returns its shape,size,and data type.

In [ ]:
import numpy as np

def array_attributes(arr):
    """
    Returns the shape, size, and data type of the given NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing the shape, size, and data type of the array.
    """
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype

    return shape, size, dtype
arr = np.array([[1.5, 2.5], [3.5, 4.5]])
attributes = array_attributes(arr)
print(attributes)

((2, 2), 4, dtype('float64'))


In [ ]:
#Q.7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
import numpy as np

def array_dimension(arr):
    """
    Returns the dimensionality of the given NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    int: The number of dimensions (axes) of the array.
    """
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print(dimension)

2


In [ ]:
#Q.8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
import numpy as np

def item_size_info(arr):
    """
    Returns the item size (size of each element) and the total size (in bytes) of the given NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing the item size in bytes and the total size in bytes of the array.
    """
    item_size = arr.itemsize
    total_size = arr.nbytes

    return item_size, total_size

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
item_size, total_size = item_size_info(arr)
print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")

Item size: 8 bytes
Total size: 48 bytes


In [ ]:
#Q.9 Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np

def array_strides(arr):
    """
    Returns the strides of the given NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing the strides of the array along each dimension.
    """
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print(strides)

(24, 8)


In [ ]:
#Q.10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Returns the shape and strides of the given NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array.

    Returns:
    tuple: A tuple containing the shape and strides of the array.
    """
    shape = arr.shape
    strides = arr.strides

    return shape, strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print(f"Shape: {shape}")
print(f"Strides: {strides}")

Shape: (2, 3)
Strides: (24, 8)


In [ ]:
#Q.11 Create a function create_zeros_array that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' elements.

In [ ]:
import numpy as np

def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with 'n' elements.

    Parameters:
    n (int): The number of elements in the array.

    Returns:
    numpy.ndarray: A NumPy array of zeros with 'n' elements.
    """
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [ ]:
#Q.12 Write a function 'create _ones_matric' that takes integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols'.

In [ ]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Create a 2D NumPy array filled with ones of size 'rows x cols'.

    Parameters:
    rows (int): The number of rows in the matrix.
    cols (int): The number of columns in the matrix.

    Returns:
    numpy.ndarray: A 2D array of shape (rows, cols) filled with ones.
    """
    return np.ones((rows, cols))

matrix = create_ones_matrix(3, 4)
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#.13 Write a function 'generate_range_array'that takes integers start, stop,and step as arguments and creates a NumPy array with a range starting from 'start',ending at stop (exclusive),and with the specified 'step'.

In [ ]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Generate a NumPy array with values starting from 'start', ending at 'stop' (exclusive),
    and with the specified 'step'.

    Parameters:
    start (int): The starting value of the range.
    stop (int): The end value of the range (exclusive).
    step (int): The step between values in the range.

    Returns:
    numpy.ndarray: An array with values from 'start' to 'stop' (exclusive) with the given 'step'.
    """
    return np.arange(start, stop, step)

array = generate_range_array(1, 10, 2)
print(array)

[1 3 5 7 9]


In [ ]:
#.14 Design a function 'genarate_linear_space' that takes two floats'start','stop',and an integer 'num' as arguments and generates a NumPy array with num equally spaced values between 'start' and 'stop'(Inclusive).

In [ ]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Generates a NumPy array with 'num' equally spaced values between 'start' and 'stop' (inclusive).

    Parameters:
    start (float): The starting value of the sequence.
    stop (float): The end value of the sequence.
    num (int): The number of equally spaced values to generate.

    Returns:
    numpy.ndarray: Array of equally spaced values.
    """
    return np.linspace(start, stop, num)

In [ ]:
arr = generate_linear_space(1.0, 10.0, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#Q.15 Create a function 'create_identity_matrix'that takes an integers'n' as pinput and generates a square identity matrix of size 'n x n'using 'numpy.eye.'

In [ ]:
import numpy as np

def create_identity_matrix(n):
    """Generates a square identity matrix of size n x n."""
    return np.eye(n)

identity_matrix = create_identity_matrix(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Q.16 Write a function that takes a python list and converts it into a NumPy array.

In [ ]:
import numpy as np

def list_to_numpy_array(py_list):
    """Converts a Python list into a NumPy array."""
    return np.array(py_list)

my_list = [1, 2, 3, 4, 5,6]
numpy_array = list_to_numpy_array(my_list)
print(numpy_array)

[1 2 3 4 5 6]


In [ ]:
#Q.17 Create a NumPy array and demonstrate the use of 'numpy.view' to create a new array object with the same data.

In [ ]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])

view_array = original_array.view()

print("Original Array:", original_array)
print("View Array:", view_array)

view_array[0] = 10

print("\nAfter modifying the view array:")
print("Original Array:", original_array)
print("View Array:", view_array)

Original Array: [1 2 3 4 5]
View Array: [1 2 3 4 5]

After modifying the view array:
Original Array: [10  2  3  4  5]
View Array: [10  2  3  4  5]


In [ ]:
#Q.18 Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    """Concatenates two NumPy arrays along a specified axis."""
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result_axis_0)

result_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", result_axis_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Q.19 Create two NumPy arrays with different shapes and concatenate them horizontally using 'numpy.concatenate'.

In [ ]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])

result = np.concatenate((array1, array2), axis=1)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated Array:\n", result)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5]
 [6]]
Concatenated Array:
 [[1 2 5]
 [3 4 6]]


In [ ]:
#Q.20 Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
import numpy as np

def vertical_stack(arrays):
    """Vertically stacks multiple NumPy arrays given as a list."""
    return np.vstack(arrays)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
array3 = np.array([[7, 8], [9, 10]])

arrays_to_stack = [array1, array2, array3]

result = vertical_stack(arrays_to_stack)

print("Vertically Stacked Array:\n", result)

Vertically Stacked Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#Q.21 Write a python function using NumPy to create an array of integers within a specified range (inclusive)with a given step size.

In [ ]:
import numpy as np

def create_integer_array(start, end, step):
    """Creates an array of integers from start to end (inclusive) with a specified step size."""
    return np.arange(start, end + 1, step)

result = create_integer_array(1, 10, 2)
print("Generated Array:", result)

Generated Array: [1 3 5 7 9]


In [ ]:
#Q.22 Write a python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
import numpy as np

def generate_equally_spaced_values(num_values=10, start=0, end=1):
    """Generates an array of equally spaced values between start and end (inclusive)."""
    return np.linspace(start, end, num_values)

result = generate_equally_spaced_values()
print("Equally Spaced Values:", result)

Equally Spaced Values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#Q.23 Write a python function using NumPy to create an array of 5 lagarithmically spaced values between 1 and 1000 (inclusive)

In [ ]:
import numpy as np

def create_log_space_array():
    return np.logspace(0, 3, num=5)

array = create_log_space_array()
print(array)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
#Q.24 Create a pandas dataframe using a NumPy array that ondition 5 rows and 3 columns,where the values are random integers between 1 and 100.

In [ ]:
import numpy as np
import pandas as pd

def create_random_dataframe():
    random_array = np.random.randint(1, 101, size=(5, 3))

    df = pd.DataFrame(random_array, columns=['Column 1', 'Column 2', 'Column 3'])

    return df

random_df = create_random_dataframe()
print(random_df)

   Column 1  Column 2  Column 3
0        30        85         7
1        44        60        74
2        24        51        10
3        36        45       100
4        91        45        52


In [ ]:
#Q.25 Write a function that takes a pandas dataframe and replaces all negative values in a specific column with zeros.use NumPy operations within the pandas dataframe.

In [ ]:
import pandas as pd
import numpy as np

def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5],
    'C': [0, 0, 0, 0, 0]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

updated_df = replace_negatives_with_zero(df, 'A')
print("\nUpdated DataFrame:")
print(updated_df)

Original DataFrame:
   A  B  C
0  1 -1  0
1 -2  2  0
2  3 -3  0
3 -4  4  0
4  5 -5  0

Updated DataFrame:
   A  B  C
0  1 -1  0
1  0  2  0
2  3 -3  0
3  0  4  0
4  5 -5  0


In [ ]:
#Q.26 Access the 3rd element from the given NumPy array.arr = np.array([10,20,30,40,50])

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("The 3rd element is:", third_element)

The 3rd element is: 30


In [ ]:
#Q.27 Retrieve the element at index (1,2)from the 2D NumPy array.arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)

The element at index (1, 2) is: 6


In [ ]:
#Q.28 Using boolean indexing,extract elements greater than 5 from the given NumPy array.arr = np.array([3,8,2,10,5,7])

In [ ]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

greater_than_five = arr[arr > 5]

print("Elements greater than 5:", greater_than_five)

Elements greater than 5: [ 8 10  7]


In [ ]:
#Q.29 Perform basic slicing to extract elements from index 2 to 5 (inclusive)from the given NumPy array. arr = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_array = arr[2:6]

print("Sliced array from index 2 to 5:", sliced_array)

Sliced array from index 2 to 5: [3 4 5 6]


In [ ]:
#.30 Slice the 2D NumPy array to extract the sub-array'[[2,3],[5,6]]'from the given array. arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]
sub_array

array([[2, 3],
       [5, 6]])

In [ ]:
#Q.31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
import numpy as np

def extract_elements(arr, indices):
    """
    Extract elements from a 2D array based on given indices.

    Parameters:
    arr (np.ndarray): A 2D NumPy array from which to extract elements.
    indices (np.ndarray): A 1D array of tuples/lists where each tuple/list contains
                          the (row, column) indices for extraction.

    Returns:
    np.ndarray: An array containing the extracted elements.
    """
    indices = np.array(indices)

    extracted_elements = arr[indices[:, 0], indices[:, 1]]

    return extracted_elements

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

indices = np.array([[0, 1],
                    [1, 2],
                    [2, 0]])

result = extract_elements(arr, indices)
print(result)

[2 6 7]


In [ ]:
#Q.32 Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [ ]:
import numpy as np

def filter_greater_than(arr, threshold):
    """
    Filter elements greater than a given threshold from a 1D array.

    Parameters:
    arr (np.ndarray): A 1D NumPy array to filter.
    threshold (float): The threshold value.

    Returns:
    np.ndarray: A 1D array containing elements greater than the threshold.
    """
    arr = np.asarray(arr)

    filtered_elements = arr[arr > threshold]

    return filtered_elements

arr = np.array([1, 5, 3, 8, 2, 7])
threshold = 4

result = filter_greater_than(arr, threshold)
print(result)

[5 8 7]


In [ ]:
#Q.33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
import numpy as np

def extract_3d_elements(arr, row_indices, col_indices, depth_indices):
    """
    Extract specific elements from a 3D array based on provided indices.

    Parameters:
    arr (np.ndarray): A 3D NumPy array from which to extract elements.
    row_indices (np.ndarray): A 1D array of row indices.
    col_indices (np.ndarray): A 1D array of column indices.
    depth_indices (np.ndarray): A 1D array of depth indices.

    Returns:
    np.ndarray: An array containing the extracted elements.
    """
    row_indices = np.asarray(row_indices)
    col_indices = np.asarray(col_indices)
    depth_indices = np.asarray(depth_indices)

    extracted_elements = arr[row_indices, col_indices, depth_indices]

    return extracted_elements

arr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]],
                 [[9, 10], [11, 12]]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 1])
depth_indices = np.array([0, 1, 0])

result = extract_3d_elements(arr, row_indices, col_indices, depth_indices)
print(result)

[ 3  6 11]


In [ ]:
#Q.34 Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:
import numpy as np

def filter_by_conditions(arr, condition1, condition2):
    """
    Return elements from an array where both conditions are satisfied.

    Parameters:
    arr (np.ndarray): A NumPy array to filter.
    condition1 (np.ndarray): A boolean array representing the first condition.
    condition2 (np.ndarray): A boolean array representing the second condition.

    Returns:
    np.ndarray: A 1D array containing elements that satisfy both conditions.
    """
    arr = np.asarray(arr)

    combined_condition = condition1 & condition2

    filtered_elements = arr[combined_condition]

    return filtered_elements

arr = np.array([1, 5, 3, 8, 2, 7])

condition1 = arr > 2
condition2 = arr < 8

result = filter_by_conditions(arr, condition1, condition2)
print(result)

[5 3 7]


In [ ]:
#Q.35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
import numpy as np

def extract_elements(arr, row_indices, col_indices):
    """
    Extracts elements from a 2D array using specified row and column indices.

    Parameters:
    arr (np.ndarray): 2D array from which to extract elements.
    row_indices (np.ndarray or list): Array or list of row indices.
    col_indices (np.ndarray or list): Array or list of column indices.

    Returns:
    np.ndarray: Array of extracted elements.
    """
    return arr[row_indices, col_indices]

if __name__ == "__main__":
    array_2d = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

    rows = np.array([0, 1, 2])
    cols = np.array([1, 0, 2])

    extracted_elements = extract_elements(array_2d, rows, cols)
    print(extracted_elements)

[2 4 9]


In [ ]:
#Q.36 Given an array arr of shape (3,3),add a scalar value of 5 to reach element using NumPy broadcasting.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
#Q.37 Consider two arrays arr1 of shape(1,3)and arr2 of shape(3,4).Multiply each row of arr 2 by the corresponding element in arr 1 using NumPy broadcasting.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

result = arr2 * arr1[:, np.newaxis]

print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [ ]:
#Q.38 Given a 1D array arr1of shape(1,4)and a 2D array arr2 of shape (4,3),add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

result = arr2 + arr1[:, :3]

print(result)

[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [ ]:
#Q.39 Consider two arrays arr1 of shape(3,1)and arr2 of shape(1,3).add these arrays using NumPy broadcasting.

In [ ]:
import numpy as np

arr1 = np.array([[1],
                 [2],
                 [3]])

arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#Q.40 Given arrays arr1 of shape (2,3)and arr2 of shape (2,2),perform multiplication using NumPy broadcasting.Handle the shape incompatibility.

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

arr2_expanded = np.repeat(arr2[:, np.newaxis, :], 3, axis=1)

result = arr1[:, :, np.newaxis] * arr2_expanded

print(result)


[[[ 7  8]
  [14 16]
  [21 24]]

 [[36 40]
  [45 50]
  [54 60]]]


In [ ]:
#.41 Calculate column-wise mean for the given array: arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_mean = np.mean(arr, axis=0)

print(column_mean)


[2.5 3.5 4.5]


In [ ]:
#Q.42 Find maximum value in each row of the given array: arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

row_max = np.max(arr, axis=1)

print(row_max)

[3 6]


In [ ]:
#Q.43 For the given array,find indices of maximum value in each column. arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_max_indices = np.argmax(arr, axis=0)

print(column_max_indices)

[1 1 1]


In [ ]:
#Q.44 For the given array,apply custom function to calculate moving sum along rows. arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

def moving_sum(arr, window_size):
    return np.convolve(arr, np.ones(window_size), mode='valid')

result = np.array([moving_sum(row, window_size=2) for row in arr])

print(result)

[[ 3.  5.]
 [ 9. 11.]]


In [ ]:
#Q.45 In the given array,check if all elements in each column are even. arr = np.array([[2,4,6],[3,5,7]])

In [ ]:
import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

all_even = np.all(arr % 2 == 0, axis=0)

print(all_even)

[False False False]


In [ ]:
#Q.46 Given a NumPy array arr,reshape it into a matrix of dimensions'm' rows and 'n'columns.Return the reshaped matrix.Original_array = np.array([1,2,3,4,5,6])

In [ ]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

def reshape_array(arr, m, n):
    if arr.size == m * n:
        reshaped_matrix = arr.reshape(m, n)
        return reshaped_matrix
    else:
        return "Cannot reshape array to the given dimensions."

m = 2
n = 3
reshaped_matrix = reshape_array(original_array, m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Q.47 Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1,2,3],[4,5,6]])

In [ ]:
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [ ]:
#Q.48 Write a function that concatenates two given arrays along a specified axis.array1 = np.array([[1,2],[3,4]]) array2 = np.array([[5,6],[7,8]])

In [ ]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0 (rows):\n", concatenated_array_axis0)

concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1 (columns):\n", concatenated_array_axis1)

Concatenated along axis 0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (columns):
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Q.49 Create a function that splits an array into multiple sub_arrays along a specified axis.Original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
import numpy as np

def split_array(arr, indices, axis):
    return np.split(arr, indices, axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_result_axis0 = split_array(original_array, 3, axis=0)
print("Split along axis 0 (rows):\n", split_result_axis0)

split_result_axis1 = split_array(original_array, 3, axis=1)
print("Split along axis 1 (columns):\n", split_result_axis1)

Split along axis 0 (rows):
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split along axis 1 (columns):
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [ ]:
#Q.50 Write a function that inserts and then deletes elements from a given array at specified indices.Original_array = np.array([1,2,3,4,5]) indices_to_insert = [2,4] values_to_insert = [10,11] indices_to_delete = [1,3]

In [ ]:
import numpy as np

def insert_and_delete(arr, insert_indices, values_to_insert, delete_indices):
    modified_array = np.insert(arr, insert_indices, values_to_insert)

    modified_array = np.delete(modified_array, delete_indices)

    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified array:", modified_array)

Modified array: [ 1 10  4 11  5]


In [ ]:
#Q.51 Create a numPy array'arr1'with random integers and another array'arr2'with integers from 1 to 10. Perform element-wise addition between'arr1'and'arr2'.

In [ ]:
import numpy as np

arr1 = np.arange(10, 0, -1)

arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)

arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
#Q.52 Genarate a NumPy array'arr1'with sequential integers from 10 to 1 and another array'arr2'with integers from 1 to 10. Subtract'arr2'from'arr1'element-wise.

In [ ]:
import numpy as np

arr1 = np.arange(10, 0, -1)

arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)

arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
#Q.53 Create a NumPy array'arr1'with andom integers and another array'arr2'with integers from 1 to 5.Perform element-wise multiplication between'arr1'and'arr2'.

In [ ]:
import numpy as np

arr1 = np.random.randint(1, 100, size=(3, 5))

arr2 = np.arange(1, 6)
arr2 = arr2.reshape(1, 5)

result = arr1 * arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)

arr1:
[[27 33 26 90 75]
 [26 46 27  9 34]
 [50 33 13 63 59]]

arr2:
[[1 2 3 4 5]]

Result of element-wise multiplication:
[[ 27  66  78 360 375]
 [ 26  92  81  36 170]
 [ 50  66  39 252 295]]


In [ ]:
#Q.54 Generate a NumPy array'arr1'with even integers from 2 to 10 and another array'arr2' with integers from 1 to 5. Perform element-wise division of'arr1'by'arr2'.

In [ ]:
import numpy as np

arr1 = np.arange(2, 11, 2)

arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)

arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [ ]:
#Q.55 Create a NumPy array'arr1'with integers from 1 to 5 and another array'arr2'with the same numbers reversed.Calculate the exponentiation of'arr1'raised to the power of'arr2'element-wise.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = arr1[::-1]

result = np.power(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of arr1 raised to the power of arr2:", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of arr1 raised to the power of arr2: [ 1 16 27 16  5]


In [ ]:
#Q.56 Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello','world','hello','numpy','hello'])

In [ ]:
import numpy as np

def count_substring(arr, substring):
    count = np.sum(np.char.count(arr, substring))
    return count

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

result = count_substring(arr, substring)
print(f"The substring '{substring}' occurs {result} times in the array.")

The substring 'hello' occurs 3 times in the array.


In [ ]:
#Q.57 Write a function that extracts uppercase characters from a NumPy array of strings.arr=np.array(['Hello','World','OpenAI','GPT'])

In [ ]:
import numpy as np

def extract_uppercase(arr):
    uppercase_chars = [''.join([char for char in string if char.isupper()]) for string in arr]
    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

result = extract_uppercase(arr)
print("Uppercase characters extracted:", result)

Uppercase characters extracted: ['H', 'W', 'OAI', 'GPT']


In [ ]:
#Q.58 Write a function that replaces occurrence of a substring in a NumPy array of strings with a new string.arr = np.array(['apple','banana','grape','pineapple'])

In [ ]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

result = replace_substring(arr, old_substring, new_substring)
print("Array after replacement:", result)

Array after replacement: ['orange' 'banana' 'grape' 'pineorange']


In [ ]:
#Q.59 Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello','World']) arr2 = np.array(['Open','AI'])

In [ ]:
import numpy as np

def concatenate_strings(arr1, arr2):
    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)
print("Concatenated array:", result)

Concatenated array: ['HelloOpen' 'WorldAI']


In [ ]:
#Q.60 Write a function that finds the length of the longest string in a NymPy array.arr = np.array(['apple','banana','grape','pineapple'])

In [ ]:
import numpy as np

def longest_string_length(arr):
    lengths = np.vectorize(len)(arr)
    return np.max(lengths)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))

9


In [ ]:
#Q.61 Create a dataset of 100 random integers between 1 and 1000.Compute the mean,median,variance,and standard deviation of the dataset using NumPy's functions.

In [ ]:
import numpy as np

dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Dataset: [235 731  58 613 911 419 270 991 707 125 854 270 161 558 104 359 144 553
 951 491 365 930 593 456 253   1 952 484 203  87 471 732 483 277 338  59
 601 930 281 926 319 534 171 403 721 219 251 990 130 533 414 601 286 725
 671  54 704 418 346 240 810 568 465 570  11 399 258 181   1   2 704 655
 392 933 789 868 553 822 287   2 994 654 313 167 570 505 695 571 954 949
 601  83 228 785 528 808 912 409 340 248]
Mean: 482.41
Median: 477.0
Variance: 81667.3419
Standard Deviation: 285.7749847344935


In [ ]:
#Q.62 Genarate an array of 50 random numbers between 1 and 100.Find the 25th and 75th percentiles of the dataset.

In [ ]:
import numpy as np

dataset = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset: [56 72 40 25 91 37 22 27 99 97 90 26  8 64 47 37 99 99 59 63 57 68 38 48
 52 53 72 53 77 19 17 44 64 63 17  7 34 16 15 46  4 97 47 96 74 10 62 45
 52 95]
25th Percentile: 28.75
75th Percentile: 71.0


In [ ]:
#Q.63 Create two arrays representing two sets of variables.Compute the correlation coefficient between these arrays using NumPy's'corrcoef'function.

In [ ]:
import numpy as np

array1 = np.random.randint(1, 101, size=10)
array2 = np.random.randint(1, 101, size=10)

correlation_matrix = np.corrcoef(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation Coefficient Matrix:\n", correlation_matrix)
print("Correlation Coefficient between array1 and array2:", correlation_matrix[0, 1])

Array 1: [ 7 91 85 29 37 39 60 21 70 18]
Array 2: [ 5 31 34 61 11  2 50 46 88 46]
Correlation Coefficient Matrix:
 [[1.         0.26428484]
 [0.26428484 1.        ]]
Correlation Coefficient between array1 and array2: 0.26428483909952677


In [ ]:
#Q.64 Create two matrices and perform matrix multiplication using NumPy's'dot'function.

In [ ]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of matrix multiplication:\n", result)

Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Result of matrix multiplication:
 [[ 58  64]
 [139 154]]


In [ ]:
#Q.65 Create an array of 50 integers between 10 and 1000.Calculate the 10th ,50th(median),and 90th percentiles along with the first and third quartiles.

In [ ]:
import numpy as np

data = np.random.randint(10, 1001, size=50)

sorted_data = np.sort(data)

percentile_10 = np.percentile(sorted_data, 10)
median_50 = np.median(sorted_data)
percentile_90 = np.percentile(sorted_data, 90)
first_quartile = np.percentile(sorted_data, 25)
third_quartile = np.percentile(sorted_data, 75)

print(f"Data: {sorted_data}")
print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {median_50}")
print(f"90th Percentile: {percentile_90}")
print(f"1st Quartile (Q1): {first_quartile}")
print(f"3rd Quartile (Q3): {third_quartile}")

Data: [ 10  62 100 104 109 132 159 169 224 238 249 277 294 296 330 348 350 361
 372 379 417 494 500 506 509 537 544 553 584 598 607 611 619 632 637 656
 681 683 698 744 747 761 785 813 817 861 861 913 928 987]
10th Percentile: 129.70000000000002
50th Percentile (Median): 523.0
90th Percentile: 821.4000000000001
1st Quartile (Q1): 294.5
3rd Quartile (Q3): 682.5


In [ ]:
#Q.66 Create a NumPy array of integers and find the index of a specific element.

In [ ]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

element_to_find = 50

index = np.where(array == element_to_find)[0]

if index.size > 0:
    print(f"The index of the element {element_to_find} is: {index[0]}")
else:
    print(f"The element {element_to_find} is not in the array.")

The index of the element 50 is: 4


In [ ]:
#Q.67 Genarate a random NumPy array and sort it in ascending order.

In [ ]:
import numpy as np

array = np.random.randint(0, 100, size=10)
print("Original Array:", array)

sorted_array = np.sort(array)
print("Sorted Array:", sorted_array)

Original Array: [65  4 39 61 50 90 20 98 94  0]
Sorted Array: [ 0  4 20 39 50 61 65 90 94 98]


In [ ]:
#Q.68 Filter elements >20 in the given NumPy array. arr = np.array([12,25,6,42,8,30])

In [ ]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_array = arr[arr > 20]

print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_array)

Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [ ]:
#Q.69 Filter elements which are divisible by 3 from a given NumPy array.arr = np.array([10,20,30,40,50])

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered_array = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_array)

Original Array: [10 20 30 40 50]
Filtered Array (elements divisible by 3): [30]


In [ ]:
#Q.70 Filter elements which are ->20 and <-40 from a given NumPy array.arr = np.array([10,20,30,40,50])

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered_array = arr[(arr > 20) | (arr < -40)]

print("Original Array:", arr)
print("Filtered Array (elements > 20 or < -40):", filtered_array)

Original Array: [10 20 30 40 50]
Filtered Array (elements > 20 or < -40): [30 40 50]


In [ ]:
#Q.71 For the given NumPy array,check its byte order using the'dtype'attribute byteorder.arr = np.array([1,2,3])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

if byte_order == '=':
    print("The byte order is native (little-endian or big-endian based on the system).")
elif byte_order == '<':
    print("The byte order is little-endian.")
elif byte_order == '>':
    print("The byte order is big-endian.")
else:
    print("The byte order is not applicable (e.g., for complex types).")

The byte order is native (little-endian or big-endian based on the system).


In [ ]:
#Q.72 For the given NumPy array,perform byte swapping in place using'byteawap()'.arr = np.array([1,2,3],dtype = np.int32)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)

arr.byteswap(inplace=True)

print("Byte-swapped Array:", arr)

Original Array: [1 2 3]
Byte-swapped Array: [16777216 33554432 50331648]


In [ ]:
#Q.73 For the given NumPy array,swap its byte order without modifying the original array using 'newbyteorder()'. arr = np.array([1,2,3],dtype=np.int32)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)

swapped_array = arr.newbyteorder()

print("Swapped Byte Order Array:", swapped_array)

Original Array: [1 2 3]
Swapped Byte Order Array: [16777216 33554432 50331648]


In [ ]:
#Q.74 For the given NumPy array and swap its byte order conditionally based on system endianness using'newbyteorder'().arr = np.array([1,2,3],dtype=np.int32)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':
    swapped_arr = arr.byteswap().newbyteorder()
else:
    swapped_arr = arr

print("Original array:", arr)
print("Byte-swapped array:", swapped_arr)

Original array: [1 2 3]
Byte-swapped array: [1 2 3]


In [ ]:
#Q.75 For the given NumPy array,check if byte swapping is necessary for the current system using'dtype' attribute'byteorder'.arr = np.array([1,2,3],dtype=np.int32)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':
    print("No byte swapping is necessary. The array is in the native byte order.")
elif arr.dtype.byteorder == '<':
    print("The array is in little-endian format.")
elif arr.dtype.byteorder == '>':
    print("The array is in big-endian format.")
else:
    print("The array is in a different format.")

No byte swapping is necessary. The array is in the native byte order.


In [ ]:
#Q.76 Create a NumPy array 'arr1'with values from 1 to 10.Create a copy of'arr1'named'copy_arr'and modify an e;ement on'copy_arr'.Check if modifying'copy_arr'affects'arr1'.

In [ ]:
import numpy as np

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 99

print("Original array (arr1):", arr1)
print("Modified copy array (copy_arr):", copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array (copy_arr): [99  2  3  4  5  6  7  8  9 10]


In [ ]:
#Q.77 Create a 2D NumPy array'matrix'of shape (3,3)with random integers.Extract a slice'view_slice'from the matrix.Modify an element in'view_slice'and observe if it changes the original'matrix'.

In [ ]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

view_slice = matrix[0:2, 0:2]

view_slice[0, 0] = 99

print("Original matrix after modifying the slice:")
print(matrix)
print("\nView slice:")
print(view_slice)

Original matrix after modifying the slice:
[[99  9  2]
 [ 9  3  6]
 [10  9  3]]

View slice:
[[99  9]
 [ 9  3]]


In [ ]:
#Q.78  Create a NumPy array'array_a'of shape(4,3)with sequential integers from 1 to 12. Extract a slice 'view_b'from 'array_a'and brodcast the addition of 5 to view_b.Check if it alters the original'array_a'

In [ ]:
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[0:2, :]

view_b += 5

print("Original array_a after modifying view_b:")
print(array_a)
print("\nView slice (view_b):")
print(view_b)

Original array_a after modifying view_b:
[[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]

View slice (view_b):
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
#Q.79 Create a NumPy array 'orig_array'of shape(2,4)with values from 1 to 8.Create a reshaped view 'reshaped_view'of shape(4,2)from orig_array.Modify an element in 'reshaped_view'and check if it reflects changes in the original 'orig_array'.

In [ ]:
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 99

print("Original Array:\n", orig_array)
print("Reshaped View:\n", reshaped_view)

Original Array:
 [[99  2  3  4]
 [ 5  6  7  8]]
Reshaped View:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [ ]:
#Q.80 Create a NumPy array'data'of shape(3,4)with random integers.Extract a copy'data'_copy'of elements grater than5.Modify an element in'data_copy'and verify if it affects the original'data'.

In [ ]:
import numpy as np

# Step 1: Create a NumPy array 'data' of shape (3, 4) with random integers from 0 to 10
data = np.random.randint(0, 11, size=(3, 4))  # Random integers between 0 and 10

# Step 2: Extract a copy 'data_copy' of elements greater than 5
data_copy = data[data > 5].copy()  # Using .copy() to create an independent array

# Step 3: Modify an element in 'data_copy'
if data_copy.size > 0:  # Ensure there is at least one element
    data_copy[0] = 99  # Change the first element

# Step 4: Verify if it affects the original 'data'
print("Original Data:\n", data)
print("Data Copy:\n", data_copy)

Original Data:
 [[ 6  2  6  0]
 [ 8  1 10  9]
 [ 5  4  8 10]]
Data Copy:
 [99  6  8 10  9  8 10]


In [ ]:
#Q.81 Create two matrices A And B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

C_add = A + B

C_sub = A - B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition (A + B):\n", C_add)
print("Subtraction (A - B):\n", C_sub)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
#Q.82 Genarate two matrices'C'(3*2)and'D'(2*4)and perform matrix multiplication.

In [ ]:
import numpy as np

C = np.random.randint(1, 10, size=(3, 2))

D = np.random.randint(1, 10, size=(2, 4))

result = np.dot(C, D)

print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Result of Matrix Multiplication (C @ D):\n", result)

Matrix C:
 [[6 7]
 [8 8]
 [4 4]]
Matrix D:
 [[9 9 5 2]
 [8 6 8 1]]
Result of Matrix Multiplication (C @ D):
 [[110  96  86  19]
 [136 120 104  24]
 [ 68  60  52  12]]


In [ ]:
#Q.83 Create a matrix'E'and find its transpose.

In [ ]:
import numpy as np

E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

E_transpose = E.T

print("Matrix E:\n", E)
print("Transpose of Matrix E:\n", E_transpose)

Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Q.84 Genarate a square matrix'F'and compute its determinant.

In [ ]:
import numpy as np

F = np.random.randint(1, 10, size=(3, 3))

det_F = np.linalg.det(F)

F, det_F

(array([[8, 2, 1],
        [5, 3, 9],
        [5, 9, 6]]),
 -443.9999999999996)

In [ ]:
#Q.85 Create a square matrix'G' and find its inverse.

In [ ]:
G = np.random.randint(1, 10, size=(3, 3))

det_G = np.linalg.det(G)

if det_G != 0:
    G_inv = np.linalg.inv(G)
else:
    G_inv = "Matrix is singular, inverse doesn't exist."

G, G_inv

(array([[9, 2, 1],
        [1, 8, 9],
        [1, 7, 3]]),
 array([[ 0.11470588, -0.00294118, -0.02941176],
        [-0.01764706, -0.07647059,  0.23529412],
        [ 0.00294118,  0.17941176, -0.20588235]]))